### ISSUE TITLE
Warning when using "Fetch - order by" without where-clause

### ISSUE THREAD

**Issue by vanjohnnl** [mrcrypster/mysqly#21]
When I use
`$rows = mysqly::fetch(
  'users',
  [
    'order_by' => 'age DESC'
  ]
);`
I get two warnings:
_Warning: Undefined variable $where in mysqly.php on line 148
Warning: Undefined variable $bind in mysqly.php on line 161_

**Comment by vanjohnnl** [comment]
Possible fix:
line 148:
Current: `if ( $where ) {`
Fix: `if ( !empty($where) ) {`

line 161:
Current: `return static::exec($sql, $bind);`
Fix: `return static::exec($sql, $bind??[]);`

**Comment by mrcrypster** [comment]
This should fix it:
https://github.com/mrcrypster/mysqly/commit/3f32c9dc3d03618cdd28ec04fe15a8a223fe93f4
