### ISSUE TITLE
RFC: Support of REPLACE INTO

### ISSUE THREAD

**Issue by vanjohnnl** [mrcrypster/mysqly#23]
The function _insert_update_ does not work with multiple rows. Could you add the support of the SQL statement _REPLACE INTO_ to your class?

I have now duplicated the insert and multi_insert-function, renamed it to (multi_)replace and changed the query within $sql to:
```
$sql = "REPLACE INTO `{$table}`
```

This is working for me, but I would lose it when installing a new release.

**Comment by mrcrypster** [comment]
Added `replace()` and `multi_replace()` methods.
